version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 123Pom
    ports:
      5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080